### ISSUE TITLE
java.io.EOFException using paho java client

### ISSUE THREAD

**Issue by mkj-git** [emqtt/emqttd#551]
I have this paho java client:

```
String topic        = "chatWith/904";
        String content      = "Message from MqttPublishSample";
        int qos             = 2;
        String broker       = "tcp://127.0.0.1:1883";
        String clientId     = "JavaSample";
        MemoryPersistence persistence = new MemoryPersistence();

        try {
            MqttClient sampleClient = new MqttClient(broker, clientId, persistence);
            MqttConnectOptions connOpts = new MqttConnectOptions();
            connOpts.setCleanSession(true);
            System.out.println("Connecting to broker: "+broker);
            sampleClient.connect(connOpts);
            System.out.println("Connected");
            System.out.println("Publishing message: "+content);
            MqttMessage message = new MqttMessage(content.getBytes());
            message.setQos(qos);
            sampleClient.publish(topic, message);
            System.out.println("Message published");
            sampleClient.disconnect();
            System.out.println("Disconnected");
            System.exit(0);
        } catch(MqttException me) {
            System.out.println("reason "+me.getReasonCode());
            System.out.println("msg "+me.getMessage());
            System.out.println("loc "+me.getLocalizedMessage());
            System.out.println("cause "+me.getCause());
            System.out.println("excep "+me);
            me.printStackTrace();
        }
```

I have this exception

```
Connecting to broker: tcp://127.0.0.1:1883
Connected
Publishing message: Message from MqttPublishSample
reason 32109
msg Connection lost
loc Connection lost
cause java.io.EOFException
excep Connection lost (32109) - java.io.EOFException
Connection lost (32109) - java.io.EOFException
	at org.eclipse.paho.client.mqttv3.internal.CommsReceiver.run(CommsReceiver.java:146)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.io.EOFException
	at java.io.DataInputStream.readByte(DataInputStream.java:267)
	at org.eclipse.paho.client.mqttv3.internal.wire.MqttInputStream.readMqttWireMessage(MqttInputStream.java:65)
	at org.eclipse.paho.client.mqttv3.internal.CommsReceiver.run(CommsReceiver.java:107)
```

**Comment by pathakNishant** [comment]
Client configuration seems perfect. Have you changed any thing in mqtt server config ?

**Comment by Nishant-Pathak** [comment]
Client configuration seems perfect. Have you changed any thing in mqtt server config ? Please share your server side logs also. Enable log for a client as:

`./bin/emqttd_ctl trace <ClientId> <LogFile>`

**Comment by mkj-git** [comment]
No i haven't change anything. Everything is default. I just downloaded the latest version & started using. From java script its working fine but from java its creating issue.

**Comment by emqplus** [comment]
@mkj-git, please tune the log level in etc/emqttd.config:
```
        {lager_console_backend, info},
```

And start the broker in console mode:
```
./bin/emqttd console
```

**Comment by mkj-git** [comment]
i did it and got something this

` [info] alarm_handler: {set,{system_memory_high_watermark,[]}}`

**Comment by mkj-git** [comment]
message.setQos(0); solved it. Can anyone explain why ? Is emqttd not supporting QOS 2 ?

**Comment by ruel** [comment]
Make sure your version in the client side matches the broker implementation. We had the same problem before, but we discovered the client was using 3.1 and broker is at 3.1.1

**Comment by emqplus** [comment]
Hi @mkj-git, please check issue #575.
